spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1066037288010-37gdmalbti04fakk3jd2tetedjrs8qq0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: Ov23li38SpPY8BhOni30
            client-secret: 10b7f64a159f53ea393c0858f0d0b1f05a492052
            scope:
              - user:email